### ISSUE TITLE
Check if folder already exists before creating new folder

### ISSUE THREAD

**Issue by josephi** [ido-ofir/core.bot#1]
It is a bit tricky when trying to create a new component with an existing name it will override the exists folder and files

**Comment by ido-ofir** [comment]
added a 'failWhenExists' option to core.write(), which will cause it to fail if the path already exists:
```js
    core.write(filePath, contentObjectOrString, { failWhenExists: true });
```
fixed implementation for all commands that generate a folder from a template.
